# Generated by Django 5.2 on 2025-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_uk',
            field=models.CharField(null=True),
        ),
    ]
